image:
  file: .gitpod.Dockerfile

tasks:
  - init: pip install --upgrade pip
  - init: pip install -r requirements.txt
  - command: python3 main.py
ports:
  - port: 5901 # if using VNC preview for Kivy GUI
    onOpen: open-preview
vscode:
  extensions:
    - ms-python.python
